name: trackmatee
description: Navigation app with dark map + Places autocomplete
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.14.0
  geolocator: ^10.1.1
  http: ^1.2.1
  google_places_flutter: ^2.0.7
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/map_dark.json
