name: trackmatee
description: A map tracking app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_polyline_points: ^2.0.0
  http: ^1.1.0
  flutter_typeahead: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
